#!/bin/sh
APP="$HOME/.local/share/pocket-update-apps"
for RUNTIME in "$APP/runtime/usr" "$HOME/.local/share/pocket-bitcoin/runtime/usr"; do
    if [ -d "$RUNTIME" ]; then
        export LD_LIBRARY_PATH="$RUNTIME/lib/arm-linux-gnueabihf"
        export PYTHONPATH="$RUNTIME/lib/python3.13:$RUNTIME/lib/python3.13/lib-dynload"
        export TCL_LIBRARY="$RUNTIME/share/tcltk/tcl8.6"
        export TK_LIBRARY="$RUNTIME/share/tcltk/tk8.6"
        break
    fi
done
exec /usr/bin/python3 "$HOME/.local/share/pocket-bitcoin/bitcoin.py"
